### ISSUE TITLE
README mentions Spring Boot

### ISSUE THREAD

**Issue by jldec** [trisberg/generator-ruby-skaffold#1]
There's a reference to Spring Boot in the README, which should be removed.

Since there's nothing Ruby-specific about this generator, perhaps we should call it "generator-skaffold-generic-k8s-deployment-service" or something like that. That way it can be used for any simple web-app type project.

**Comment by trisberg** [comment]
Good point, updated this to be generic web app, renamed it and also updated tss to use this renamed generator
